In [4]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
# from data_profiling import ProfileReport

In [6]:
df = pd.read_csv('messy_customer_orders.csv')
df.head()

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned
0,ORD-004208,CUST-6426,22/07/2022,canada,Clothing,Notebook Set,4,38.57,154.28,Shipped,PayPal,TRUE
1,ORD-006584,NaN,10-12-2023,NaN,NaN,Backpack,-2,NaN,NaN,Shipped,Cash,True
2,ORD-013539,NaN,26/07/2023,NaN,NaN,Travel Mug,9,NaN,NaN,Delivered,PayPal,1
3,ORD-038448,CUST-2286,02-18-2022,Germany,clothing,Bluetooth Speaker,2,192.93,385.86,shipped,Cash,No
4,ORD-022268,CUST-6074,18/06/2024,Australia,Clothing,Office Chair,5,99.7,446.80,pending,Bank Transfer,Y

In [7]:
# profile = ProfileReport(df,)

In [8]:
df.shape

(51000, 12)

In [9]:
df.dtypes

order_id              str
customer_id           str
order_date            str
country               str
category              str
product               str
quantity            int64
unit_price            str
total_amount      float64
status                str
payment_method        str
is_returned           str
dtype: object

In [11]:
df.isnull().sum() # missing values

order_id             0
customer_id       2033
order_date           0
country           2540
category          3052
product              0
quantity             0
unit_price        2033
total_amount      1528
status               0
payment_method       0
is_returned          0
dtype: int64

In [12]:
df.head(10)

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned
0,ORD-004208,CUST-6426,22/07/2022,canada,Clothing,Notebook Set,4,38.57,154.28,Shipped,PayPal,TRUE
1,ORD-006584,NaN,10-12-2023,NaN,NaN,Backpack,-2,NaN,NaN,Shipped,Cash,True
2,ORD-013539,NaN,26/07/2023,NaN,NaN,Travel Mug,9,NaN,NaN,Delivered,PayPal,1
3,ORD-038448,CUST-2286,02-18-2022,Germany,clothing,Bluetooth Speaker,2,192.93,385.86,shipped,Cash,No
4,ORD-022268,CUST-6074,18/06/2024,Australia,Clothing,Office Chair,5,99.7,446.80,pending,Bank Transfer,Y
5,ORD-003919,NaN,03/02/2023,NaN,NaN,Coffee Table,2,NaN,NaN,Pending,Cash,True
6,ORD-033802,CUST-1788,23/09/2023,US,Home & Garden,LED Strip Lights,7,$64.81,453.67,Pending,PayPal,no
7,ORD-034516,CUST-5877,10/07/2022,NaN,NaN,Python Programming Book,4,208.64,834.56,Cancelled,Credit Card,True
8,ORD-026972,CUST-1165,15/04/2022,United Kingdom,Clothing,Laptop Stand,2,$259.61,519.22,Pending,Cash,False
9,ORD-022533,CUST-2637,21 Jun 2022,United Kingdom,books,Phone Case,1,"$1,920.61",1920.61,delivered,PayPal,False

In [13]:
df.columns = (
    df.columns.str.replace(' ','_').str.lower().str.strip() # replaces spaces with underscores, makes all columns to lower case and removes any white spacses using strip()
)

In [14]:
df.columns

Index(['order_id', 'customer_id', 'order_date', 'country', 'category',
       'product', 'quantity', 'unit_price', 'total_amount', 'status',
       'payment_method', 'is_returned'],
      dtype='str')

In [ ]:
missing = df.isnull().mean()*100 # average of missing values is multiplied by 100 so giving us a percentage
missing[missing>0].sort_values(ascending = False)

category        5.984314
country         4.980392
customer_id     3.986275
unit_price      3.986275
total_amount    2.996078
dtype: float64

In [ ]:
n_duplicates = df.duplicated().sum() # duplicate means everything in the entire row is the same
n_duplicates

np.int64(1000)

In [19]:
df[df.duplicated(keep = False)].sort_values(by = list(df.columns)).head(10)

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned
17684,ORD-000086,CUST-6333,25 Nov 2023,United States,Sports,Notebook Set,9,248.98,2240.82,pending,Bank Transfer,TRUE
18714,ORD-000086,CUST-6333,25 Nov 2023,United States,Sports,Notebook Set,9,248.98,2240.82,pending,Bank Transfer,TRUE
1064,ORD-000093,CUST-3114,2024-01-11,Australia,Sports,Travel Mug,7,$246.96,1728.72,Cancelled,Cash,False
18156,ORD-000093,CUST-3114,2024-01-11,Australia,Sports,Travel Mug,7,$246.96,1728.72,Cancelled,Cash,False
11092,ORD-000109,CUST-0585,2022-12-25,USA,Sports,Python Programming Book,3,244.67,734.01,Delivered,PayPal,TRUE
21365,ORD-000109,CUST-0585,2022-12-25,USA,Sports,Python Programming Book,3,244.67,734.01,Delivered,PayPal,TRUE
17112,ORD-000122,CUST-5638,18/06/2023,germany,ELECTRONICS,Laptop Stand,9,147.14,1324.26,DELIVERED,PayPal,yes
41112,ORD-000122,CUST-5638,18/06/2023,germany,ELECTRONICS,Laptop Stand,9,147.14,1324.26,DELIVERED,PayPal,yes
28614,ORD-000392,CUST-0765,06-11-2022,canada,Books,USB Hub,4,111.76,447.04,Delivered,Credit Card,No
38436,ORD-000392,CUST-0765,06-11-2022,canada,Books,USB Hub,4,111.76,447.04,Delivered,Credit Card,No

In [24]:
df = df.drop_duplicates()

In [25]:
df.shape

(50000, 12)

In [26]:
df.isnull().sum()

order_id             0
customer_id       2000
order_date           0
country           2500
category          3000
product              0
quantity             0
unit_price        2000
total_amount      1500
status               0
payment_method       0
is_returned          0
dtype: int64

In [28]:
# replacing missing values with median

df= df.copy()

# numeric columns
for col in ['total_amount']:
    df[col] = df[col].fillna(df[col].median())
# categorical columns:
categorical_cols = ['customer_id','country','category']

df[categorical_cols] = df[categorical_cols].fillna("Unkown")

In [29]:
print(df.isnull().sum()[df.isnull().sum()>0])

unit_price    2000
dtype: int64

In [30]:
# standardizing the text:

df.head(20)

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned
0,ORD-004208,CUST-6426,22/07/2022,canada,Clothing,Notebook Set,4,38.57,154.280,Shipped,PayPal,TRUE
1,ORD-006584,Unkown,10-12-2023,Unkown,Unkown,Backpack,-2,NaN,690.105,Shipped,Cash,True
2,ORD-013539,Unkown,26/07/2023,Unkown,Unkown,Travel Mug,9,NaN,690.105,Delivered,PayPal,1
3,ORD-038448,CUST-2286,02-18-2022,Germany,clothing,Bluetooth Speaker,2,192.93,385.860,shipped,Cash,No
4,ORD-022268,CUST-6074,18/06/2024,Australia,Clothing,Office Chair,5,99.7,446.800,pending,Bank Transfer,Y
5,ORD-003919,Unkown,03/02/2023,Unkown,Unkown,Coffee Table,2,NaN,690.105,Pending,Cash,True
6,ORD-033802,CUST-1788,23/09/2023,US,Home & Garden,LED Strip Lights,7,$64.81,453.670,Pending,PayPal,no
7,ORD-034516,CUST-5877,10/07/2022,Unkown,Unkown,Python Programming Book,4,208.64,834.560,Cancelled,Credit Card,True
8,ORD-026972,CUST-1165,15/04/2022,United Kingdom,Clothing,Laptop Stand,2,$259.61,519.220,Pending,Cash,False
9,ORD-022533,CUST-2637,21 Jun 2022,United Kingdom,books,Phone Case,1,"$1,920.61",1920.610,delivered,PayPal,False
10,ORD-003280,Unkown,28/06/2022,Unkown,Unkown,USB Hub,7,NaN,690.105,Shipped,PayPal,False
11,ORD-041488,CUST-4357,"May 23, 2022",AUS,SPORTS,Resistance Bands,1,"$1,213.34",1213.340,Cancelled,Bank Transfer,False
12,ORD-030776,CUST-5440,05-30-2022,United States,Home and Garden,Office Chair,5,38.29,191.450,cancelled,Credit Card,Yes
13,ORD-036314,CUST-2500,02-08-2024,U.K.,home & garden,Travel Mug,7,$284.47,1991.290,shipped,Credit Card,0
14,ORD-039503,CUST-3640,11 Oct 2022,germany,Sports,Coffee Table,8,"$1,295.01",10360.080,Cancelled,Bank Transfer,No
15,ORD-029721,CUST-6770,"September 29, 2023",U.S.A,BOOKS,Wireless Headphones,2,£174.02,348.040,shipped,Credit Card,0
16,ORD-048728,CUST-5152,2023-04-13,United States,clothing,Water Bottle,2,124.49,248.980,Cancelled,Bank Transfer,TRUE
17,ORD-020825,CUST-5544,25/11/2022,AUS,Sports,Travel Mug,8,138.19,1105.520,cancelled,Bank Transfer,yes
18,ORD-025971,Unkown,2022-10-12,Unkown,Unkown,Notebook Set,4,NaN,690.105,delivered,Cash,False
19,ORD-018155,CUST-3717,"December 14, 2023",UK,home & garden,Yoga Mat,8,$299.23,2393.840,Pending,PayPal,N

In [31]:
for col in ['category','country','status']:
    df[col] = df[col].str.strip().str.lower()

# map top canonical values:
category_map = {
    'electronics': 'Electronics',
    'clothing': 'Clothing',
    'home & garden':'Home & Garden',
    'home and garden':'Home & Garden',
    'sports':'Sports',
    'SPORTS':'Sports',
    'books':'Books',
    'unkown':'Unknown'
}

status_map = {
    'delivered':'Delivered',
    'pending':'Pending',
    'shipped':'Shipped',
    'cancelled':'Cancelled'
}

country_map = {
    'united states': 'United States', 'us':'United States',
    'u.s.a':'United States', 'usa':'United States',
    'united kingdom':'United Kingdom','uk':'United Kingdom','u.k.':'United Kingdom',
    'australia':'Australia','aus':'Australia',
    'canada':'Canada',
    'germany':'Germany','de': 'Germany',
    'unkown':'Unkown'
}

df['category'] = df['category'].map(category_map).fillna(df['category'])
df['staus'] = df['status'].map(status_map).fillna(df['status'])
df['country'] = df['country'].map(country_map).fillna(df['country'])

In [32]:
df.head(10)

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned,staus
0,ORD-004208,CUST-6426,22/07/2022,Canada,Clothing,Notebook Set,4,38.57,154.280,shipped,PayPal,TRUE,Shipped
1,ORD-006584,Unkown,10-12-2023,Unkown,Unknown,Backpack,-2,NaN,690.105,shipped,Cash,True,Shipped
2,ORD-013539,Unkown,26/07/2023,Unkown,Unknown,Travel Mug,9,NaN,690.105,delivered,PayPal,1,Delivered
3,ORD-038448,CUST-2286,02-18-2022,Germany,Clothing,Bluetooth Speaker,2,192.93,385.860,shipped,Cash,No,Shipped
4,ORD-022268,CUST-6074,18/06/2024,Australia,Clothing,Office Chair,5,99.7,446.800,pending,Bank Transfer,Y,Pending
5,ORD-003919,Unkown,03/02/2023,Unkown,Unknown,Coffee Table,2,NaN,690.105,pending,Cash,True,Pending
6,ORD-033802,CUST-1788,23/09/2023,United States,Home & Garden,LED Strip Lights,7,$64.81,453.670,pending,PayPal,no,Pending
7,ORD-034516,CUST-5877,10/07/2022,Unkown,Unknown,Python Programming Book,4,208.64,834.560,cancelled,Credit Card,True,Cancelled
8,ORD-026972,CUST-1165,15/04/2022,United Kingdom,Clothing,Laptop Stand,2,$259.61,519.220,pending,Cash,False,Pending
9,ORD-022533,CUST-2637,21 Jun 2022,United Kingdom,Books,Phone Case,1,"$1,920.61",1920.610,delivered,PayPal,False,Delivered

In [33]:
df['unit_price'] = df['unit_price'].astype(str).str.replace(r'[$£,]','',regex=True).str.strip()
df['unit_price'] = pd.to_numeric(df['unit_price'], errors = 'coerce')

In [34]:
df.head(10)

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned,staus
0,ORD-004208,CUST-6426,22/07/2022,Canada,Clothing,Notebook Set,4,38.57,154.280,shipped,PayPal,TRUE,Shipped
1,ORD-006584,Unkown,10-12-2023,Unkown,Unknown,Backpack,-2,NaN,690.105,shipped,Cash,True,Shipped
2,ORD-013539,Unkown,26/07/2023,Unkown,Unknown,Travel Mug,9,NaN,690.105,delivered,PayPal,1,Delivered
3,ORD-038448,CUST-2286,02-18-2022,Germany,Clothing,Bluetooth Speaker,2,192.93,385.860,shipped,Cash,No,Shipped
4,ORD-022268,CUST-6074,18/06/2024,Australia,Clothing,Office Chair,5,99.70,446.800,pending,Bank Transfer,Y,Pending
5,ORD-003919,Unkown,03/02/2023,Unkown,Unknown,Coffee Table,2,NaN,690.105,pending,Cash,True,Pending
6,ORD-033802,CUST-1788,23/09/2023,United States,Home & Garden,LED Strip Lights,7,64.81,453.670,pending,PayPal,no,Pending
7,ORD-034516,CUST-5877,10/07/2022,Unkown,Unknown,Python Programming Book,4,208.64,834.560,cancelled,Credit Card,True,Cancelled
8,ORD-026972,CUST-1165,15/04/2022,United Kingdom,Clothing,Laptop Stand,2,259.61,519.220,pending,Cash,False,Pending
9,ORD-022533,CUST-2637,21 Jun 2022,United Kingdom,Books,Phone Case,1,1920.61,1920.610,delivered,PayPal,False,Delivered

In [36]:
bool_map = {
    'Yes':True, 'yes':True, 'Y':True, 'y':True,
    'TRUE':True, 'True':True, 'true':True, '1':True, 1:True,True:True,
    'No':False, 'no':False, 'N':False,'n':False,
    'False':False,'FALSE':False,'false':False,'0':False,0:False,False:False
}

In [39]:
df['is_returned'] = df['is_returned'].map(bool_map).fillna(False)

In [40]:
df.head(10)

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned,staus
0,ORD-004208,CUST-6426,22/07/2022,Canada,Clothing,Notebook Set,4,38.57,154.280,shipped,PayPal,True,Shipped
1,ORD-006584,Unkown,10-12-2023,Unkown,Unknown,Backpack,-2,NaN,690.105,shipped,Cash,True,Shipped
2,ORD-013539,Unkown,26/07/2023,Unkown,Unknown,Travel Mug,9,NaN,690.105,delivered,PayPal,True,Delivered
3,ORD-038448,CUST-2286,02-18-2022,Germany,Clothing,Bluetooth Speaker,2,192.93,385.860,shipped,Cash,False,Shipped
4,ORD-022268,CUST-6074,18/06/2024,Australia,Clothing,Office Chair,5,99.70,446.800,pending,Bank Transfer,True,Pending
5,ORD-003919,Unkown,03/02/2023,Unkown,Unknown,Coffee Table,2,NaN,690.105,pending,Cash,True,Pending
6,ORD-033802,CUST-1788,23/09/2023,United States,Home & Garden,LED Strip Lights,7,64.81,453.670,pending,PayPal,False,Pending
7,ORD-034516,CUST-5877,10/07/2022,Unkown,Unknown,Python Programming Book,4,208.64,834.560,cancelled,Credit Card,True,Cancelled
8,ORD-026972,CUST-1165,15/04/2022,United Kingdom,Clothing,Laptop Stand,2,259.61,519.220,pending,Cash,False,Pending
9,ORD-022533,CUST-2637,21 Jun 2022,United Kingdom,Books,Phone Case,1,1920.61,1920.610,delivered,PayPal,False,Delivered

In [41]:
df['order_date'] = pd.to_datetime(df['order_date'], dayfirst = True, errors='coerce')
failed = df['order_date'].isnull().sum()

In [44]:
print(failed)

37544

In [43]:
df.head(10)

,order_id,customer_id,order_date,country,category,product,quantity,unit_price,total_amount,status,payment_method,is_returned,staus
0,ORD-004208,CUST-6426,2022-07-22,Canada,Clothing,Notebook Set,4,38.57,154.280,shipped,PayPal,True,Shipped
1,ORD-006584,Unkown,NaT,Unkown,Unknown,Backpack,-2,NaN,690.105,shipped,Cash,True,Shipped
2,ORD-013539,Unkown,2023-07-26,Unkown,Unknown,Travel Mug,9,NaN,690.105,delivered,PayPal,True,Delivered
3,ORD-038448,CUST-2286,NaT,Germany,Clothing,Bluetooth Speaker,2,192.93,385.860,shipped,Cash,False,Shipped
4,ORD-022268,CUST-6074,2024-06-18,Australia,Clothing,Office Chair,5,99.70,446.800,pending,Bank Transfer,True,Pending
5,ORD-003919,Unkown,2023-02-03,Unkown,Unknown,Coffee Table,2,NaN,690.105,pending,Cash,True,Pending
6,ORD-033802,CUST-1788,2023-09-23,United States,Home & Garden,LED Strip Lights,7,64.81,453.670,pending,PayPal,False,Pending
7,ORD-034516,CUST-5877,2022-07-10,Unkown,Unknown,Python Programming Book,4,208.64,834.560,cancelled,Credit Card,True,Cancelled
8,ORD-026972,CUST-1165,2022-04-15,United Kingdom,Clothing,Laptop Stand,2,259.61,519.220,pending,Cash,False,Pending
9,ORD-022533,CUST-2637,NaT,United Kingdom,Books,Phone Case,1,1920.61,1920.610,delivered,PayPal,False,Delivered

In [45]:
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_of_week'] = df['order_date'].dt.day_name()

In [49]:
df[['order_date','order_year','order_month','order_of_week']].head()

  order_date  order_year  order_month order_of_week
0 2022-07-22      2022.0          7.0        Friday
1        NaT         NaN          NaN           NaN
2 2023-07-26      2023.0          7.0     Wednesday
3        NaT         NaN          NaN           NaN
4 2024-06-18      2024.0          6.0       Tuesday

In [54]:
df.loc[df['quantity']<=0, ['order_id','product','quantity','unit_price','total_amount']]

         order_id              product  quantity  unit_price  total_amount
1      ORD-006584             Backpack        -2         NaN       690.105
193    ORD-040428     Resistance Bands         0      258.43         0.000
306    ORD-029737             Yoga Mat        -3         NaN       690.105
449    ORD-049440           Phone Case         0     1212.28         0.000
638    ORD-013603             Yoga Mat         0      110.68         0.000
...           ...                  ...       ...         ...           ...
50364  ORD-021365     LED Strip Lights         0     1264.40         0.000
50446  ORD-032321           Sunglasses        -3      179.77      -539.310
50576  ORD-025548  Mechanical Keyboard        -4       18.39       -73.560
50695  ORD-038361           Phone Case        -1      213.67      -213.670
50923  ORD-033764        Monitor Stand         0      256.47         0.000

[500 rows x 5 columns]